apiVersion: v1
kind: Namespace
metadata:
  name: gabin-namespace
  labels:
    name: gabin-td
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gabin-quota
spec:
  hard:
    cpu: "3"
    memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabin-deployment
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: dockercloud/hello-world
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: gabin-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: hello-world
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ianlcz-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: gabin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gabin-service
                port:
                  number: 80
