version:  '3.7'

services:
  mysql:
    build:
          context: ./my-context
          dockerfile: dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backups:/backups
